packages:
  - "."

allowBuilds:
  core-js: true
  protobufjs: true
  esbuild: true
  lightninghtcss: true

onlyBuiltDependencies:
  - core-js
  - protobufjs
  - esbuild
  - lightningcss

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
